use crate::i18n::{tr, trf};
use crate::{
    config::Console,
    protocol::{Command, Connection, Event, Resume},
};
use anyhow::Result;
use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

pub const SCROLLBACK: usize = 5000;
#[derive(Default)]
struct Boundary {
    escape: u8,
    utf8: u8,
}
impl Boundary {
    fn feed(&mut self, bytes: &[u8]) {
        for &b in bytes {
            if self.utf8 > 0 {
                if b & 0xc0 == 0x80 {
                    self.utf8 -= 1;
                    continue;
                }
                self.utf8 = 0;
            }
            self.escape = match self.escape {
                0 if b == 27 => 1,
                0 => {
                    self.utf8 = match b {
                        0xc2..=0xdf => 1,
                        0xe0..=0xef => 2,
                        0xf0..=0xf4 => 3,
                        _ => 0,
                    };
                    0
                }
                1 => match b {
                    b'[' => 2,
                    b']' | b'P' | b'^' | b'_' => 3,
                    27 => 1,
                    _ => 0,
                },
                2 => {
                    if (0x40..=0x7e).contains(&b) || b == 24 || b == 26 {
                        0
                    } else if b == 27 {
                        1
                    } else {
                        2
                    }
                }
                3 => match b {
                    7 | 24 | 26 => 0,
                    27 => 4,
                    _ => 3,
                },
                _ => {
                    if b == b'\\' {
                        0
                    } else if b == 27 {
                        4
                    } else {
                        3
                    }
                }
            };
        }
    }
    fn complete(&self) -> bool {
        self.escape == 0 && self.utf8 == 0
    }
}
pub const BANNER: [&str; 5] = [
    "████  ████ ██  ██ █████ █████ ████  ██   ██",
    "██ ██ ██    ████    ██  ██    ██ ██ ███ ███",
    "████  ████   ██     ██  ████  ████  ██ █ ██",
    "██      ██  ████    ██  ██    ██ ██ ██   ██",
    "██    ████ ██  ██   ██  █████ ██ ██ ██   ██",
];
pub fn banner() -> String {
    let mut s = String::from("\r\n");
    for (i, line) in BANNER.iter().enumerate() {
        s.push_str(&format!(
            "\x1b[38;2;{};{};{}m{line}\x1b[0m\r\n",
            101 + i * 23,
            214 - i * 15,
            232 + i * 5
        ));
    }
    s.push_str(&format!(
        "{}\r\n{}\r\n\r\n",
        tr("brand.credit"),
        tr("brand.license")
    ));
    s
}
pub struct Pane {
    pub id: u64,
    pub console_id: u64,
    pub title: String,
    pub parser: vt100::Parser,
    pub connection: Option<Connection>,
    pub status: String,
    pub online: bool,
    pub unread: bool,
    pub resume: Option<Resume>,
    pub caps: u32,
    pub server: String,
    pub dimensions: (u16, u16),
    pub report: Option<String>,
    pub pending_command: Option<String>,
    pub remote_sid: Option<u32>,
    pub output_revision: u64,
    last_cr: bool,
    boundary: Boundary,
}
impl Pane {
    pub fn new(id: u64, console: &Console, demo: bool) -> Self {
        let mut parser = vt100::Parser::new(24, 80, SCROLLBACK);
        parser.process(banner().as_bytes());
        let connection = if demo {
            None
        } else {
            Some(Connection::start(console.clone(), 24, 80, None))
        };
        let mut p = Self {
            id,
            console_id: console.id,
            title: trf("pane.title", &[id.to_string()]),
            parser,
            connection,
            status: if demo {
                tr("status.demo")
            } else {
                tr("status.connecting")
            },
            online: false,
            unread: false,
            resume: None,
            caps: 0,
            server: String::new(),
            dimensions: (24, 80),
            report: None,
            pending_command: None,
            remote_sid: None,
            output_revision: 0,
            last_cr: false,
            boundary: Boundary::default(),
        };
        if demo {
            p.parser
                .process(b"PS5:~ $ uname\r\nPlayStation 5 / PSXTerm 0.1.0\r\nPS5:~ $ ls\r\n\x1b[34mprojects/\x1b[0m  \x1b[32mcli_test\x1b[0m  README.md\r\nPS5:~ $ ");
        }
        p
    }
    pub fn notice(&mut self, message: &str) {
        // Messages generated by the client cannot inject terminal control sequences.
        let text: String = message.chars().filter(|c| !c.is_control()).collect();
        self.parser.process(format!("\r\n[{text}]\r\n").as_bytes());
        self.output_revision = self.output_revision.wrapping_add(1);
    }
    pub fn poll(&mut self, active: bool) -> bool {
        self.poll_with_budget(active, true, &mut crate::work::Budget::new())
            .0
    }
    pub(crate) fn poll_with_budget(
        &mut self,
        active: bool,
        visible: bool,
        budget: &mut crate::work::Budget,
    ) -> (bool, bool) {
        let mut changed = active && self.unread;
        let mut pending = false;
        let mut processed = 0;
        let mut ended = false;
        let mut bytes = 0;
        // A busy pane yields to the others as well as to input. Receive only
        // what can be processed now: unconsumed events stay in the bounded FIFO.
        for _ in 0..8 {
            if bytes >= crate::protocol::MAX_PAYLOAD || !budget.available() {
                pending = self.connection.is_some();
                break;
            }
            let Some(e) = self.connection.as_ref().and_then(|c| c.rx.try_recv().ok()) else {
                break;
            };
            let size = match &e {
                Event::Output(bytes) => bytes.len(),
                _ => 0,
            };
            bytes += size;
            processed += 1;
            budget.record(size);
            changed |= !matches!(&e, Event::Output(_));
            match e {
                Event::Connected(sid, server) => {
                    self.online = true;
                    self.remote_sid = Some(sid);
                    self.status = trf("status.online", &[sid.to_string()]);
                    self.server = server;
                    let _ = self.send(Command::Resize(self.dimensions.0, self.dimensions.1));
                    if let Some(command) = self.pending_command.take()
                        && let Err(e) =
                            self.send(Command::Input(format!("{command}\n").into_bytes()))
                    {
                        self.notice(&e.to_string());
                    }
                }
                Event::Output(bytes) => {
                    if !bytes.is_empty() {
                        self.output(&bytes);
                        changed |= visible || (!active && !self.unread);
                        if !active {
                            self.unread = true;
                        }
                    }
                }
                Event::Resume(r) => self.resume = Some(r),
                Event::Capabilities(c) => self.caps = c,
                Event::Exit(code, shell) => {
                    if code != 0 {
                        self.notice(&trf("status.exit", &[code.to_string()]));
                        if !active {
                            self.unread = true;
                        }
                    }
                    if shell {
                        self.resume = None;
                        self.status = tr("status.shell_exit");
                        self.online = false;
                    }
                }
                Event::Pong(d) => self.status = trf("status.ping", &[d.as_millis().to_string()]),
                Event::Sessions(s) => self.report = Some(s),
                Event::Error(s) => {
                    self.notice(&s);
                    if !active {
                        self.unread = true;
                    }
                    self.status = tr("status.offline");
                    self.online = false;
                }
                Event::Disconnected => {
                    ended = true;
                    if self.online {
                        self.status = tr("status.disconnected");
                    }
                    self.online = false;
                }
            }
        }
        if ended {
            self.connection = None;
        }
        if active {
            self.unread = false;
        }
        (
            changed,
            (pending || processed == 8) && self.connection.is_some(),
        )
    }
    pub fn send(&mut self, command: Command) -> Result<()> {
        if !self.online {
            anyhow::bail!(tr("error.offline"));
        }
        self.connection
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!(tr("error.no_terminal")))?
            .send(command)
    }
    pub fn output(&mut self, bytes: &[u8]) {
        // Match the existing raw-mode client: bare LF starts a new line.
        // Track CR across frame boundaries to preserve an existing CRLF.
        let mut normalized = Vec::with_capacity(bytes.len());
        for b in bytes {
            if *b == b'\n' && !self.last_cr {
                normalized.push(b'\r');
            }
            normalized.push(*b);
            self.last_cr = *b == b'\r';
        }
        self.parser.process(&normalized);
        self.boundary.feed(&normalized);
        if !bytes.is_empty() {
            self.output_revision = self.output_revision.wrapping_add(1);
        }
    }
    pub fn resize(&mut self, rows: u16, cols: u16) {
        let size = (rows.max(1), cols.max(1));
        if size == self.dimensions {
            return;
        }
        // vt100 truncates bottom rows on shrink. Move the live cursor/output
        // into the new viewport first, retaining displaced rows in scrollback.
        // Alternate-screen applications handle their own layout after RESIZE.
        let cursor_row = self.parser.screen().cursor_position().0;
        if size.0 < self.dimensions.0
            && cursor_row >= size.0
            && !self.parser.screen().alternate_screen()
            && self.boundary.complete()
        {
            let shift = cursor_row - size.0 + 1;
            self.parser
                .process(format!("\x1b[{shift}S\x1b[{shift}A").as_bytes());
        }
        self.dimensions = size;
        self.parser.screen_mut().set_size(size.0, size.1);
        if self.online
            && let Err(e) = self.send(Command::Resize(size.0, size.1))
        {
            self.status = e.to_string();
        }
    }
    pub fn reconnect(&mut self, console: &Console) {
        if self.connection.is_some() {
            self.notice(&tr("status.busy"));
            return;
        }
        self.connection = Some(Connection::start(
            console.clone(),
            self.dimensions.0,
            self.dimensions.1,
            self.resume.clone(),
        ));
        self.status = tr("status.connecting");
    }
    pub fn scroll(&mut self, delta: isize) {
        let offset = self
            .parser
            .screen()
            .scrollback()
            .saturating_add_signed(delta);
        self.parser.screen_mut().set_scrollback(offset);
    }
    pub fn input(&mut self, key: KeyEvent) -> Result<()> {
        self.parser.screen_mut().set_scrollback(0);
        if key.modifiers.contains(KeyModifiers::CONTROL) && key.code == KeyCode::Char('d') {
            return self.send(Command::Input(vec![]));
        }
        if let Some(bytes) = encode_key(key, self.parser.screen().application_cursor()) {
            self.send(Command::Input(bytes))?;
        }
        Ok(())
    }
    pub fn paste(&mut self, text: &str) -> Result<()> {
        let bytes = if self.parser.screen().bracketed_paste() {
            format!("\x1b[200~{text}\x1b[201~").into_bytes()
        } else {
            text.as_bytes().to_vec()
        };
        if bytes.len() > crate::protocol::MAX_PAYLOAD {
            anyhow::bail!(tr("error.paste"));
        }
        self.send(Command::Input(bytes))
    }
}
pub fn encode_key(key: KeyEvent, application: bool) -> Option<Vec<u8>> {
    let m = key.modifiers;
    let mut bytes = match key.code {
        KeyCode::Char(c) if m.contains(KeyModifiers::CONTROL) => {
            let c = c.to_ascii_lowercase();
            match c {
                'a'..='z' => vec![c as u8 - b'a' + 1],
                ' ' | '@' => vec![0],
                '[' => vec![27],
                '\\' => vec![28],
                ']' => vec![29],
                '^' => vec![30],
                '_' => vec![31],
                _ => return None,
            }
        }
        KeyCode::Char(c) => c.to_string().into_bytes(),
        KeyCode::Enter => vec![b'\r'],
        KeyCode::Backspace => vec![127],
        KeyCode::Tab => vec![b'\t'],
        KeyCode::Esc => vec![27],
        KeyCode::Up
        | KeyCode::Down
        | KeyCode::Right
        | KeyCode::Left
        | KeyCode::Home
        | KeyCode::End => {
            let letter = match key.code {
                KeyCode::Up => 'A',
                KeyCode::Down => 'B',
                KeyCode::Right => 'C',
                KeyCode::Left => 'D',
                KeyCode::Home => 'H',
                _ => 'F',
            };
            let modifier = 1
                + u8::from(m.contains(KeyModifiers::SHIFT))
                + 2 * u8::from(m.contains(KeyModifiers::ALT))
                + 4 * u8::from(m.contains(KeyModifiers::CONTROL));
            if modifier > 1 {
                format!("\x1b[1;{modifier}{letter}").into_bytes()
            } else {
                format!("\x1b{}{letter}", if application { 'O' } else { '[' }).into_bytes()
            }
        }
        KeyCode::Delete => b"\x1b[3~".to_vec(),
        KeyCode::Insert => b"\x1b[2~".to_vec(),
        KeyCode::PageUp => b"\x1b[5~".to_vec(),
        KeyCode::PageDown => b"\x1b[6~".to_vec(),
        KeyCode::BackTab => b"\x1b[Z".to_vec(),
        _ => return None,
    };
    if m.contains(KeyModifiers::ALT) && matches!(key.code, KeyCode::Char(_)) {
        bytes.insert(0, 27);
    }
    Some(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn banner_and_ansi_colors_are_real_terminal_cells() {
        let mut p = vt100::Parser::new(24, 80, 10);
        p.process(banner().as_bytes());
        assert!(p.screen().contents().contains("seregonwar"));
        assert!(p.screen().contents().contains("GPLv3"));
        assert_eq!(
            p.screen().cell(1, 0).unwrap().fgcolor(),
            vt100::Color::Rgb(101, 214, 232)
        );
        p.process(b"\x1b[2J\x1b[H\x1b[31mred\x1b[0m");
        assert_eq!(
            p.screen().cell(0, 0).unwrap().fgcolor(),
            vt100::Color::Idx(1)
        );
    }
    #[test]
    fn shell_keys_and_application_cursor() {
        let key = |code, modifiers| KeyEvent::new(code, modifiers);
        assert_eq!(
            encode_key(key(KeyCode::Char('c'), KeyModifiers::CONTROL), false).unwrap(),
            vec![3]
        );
        assert_eq!(
            encode_key(key(KeyCode::Up, KeyModifiers::NONE), true).unwrap(),
            b"\x1bOA"
        );
        assert_eq!(
            encode_key(key(KeyCode::Left, KeyModifiers::CONTROL), false).unwrap(),
            b"\x1b[1;5D"
        );
        assert_eq!(
            encode_key(key(KeyCode::Char('è'), KeyModifiers::NONE), false).unwrap(),
            "è".as_bytes()
        );
    }
    #[test]
    fn bare_lf_and_fragmented_crlf_start_at_column_zero() {
        let c = Console {
            id: 1,
            name: "test".into(),
            host: "localhost".into(),
            port: 2323,
            token: None,
            token_env: None,
        };
        let mut pane = Pane::new(1, &c, true);
        pane.parser.process(b"\x1b[2J\x1b[H");
        pane.output(b"one\ntwo\r");
        pane.output(b"\nthree\n");
        assert_eq!(pane.parser.screen().contents(), "one\ntwo\nthree");
        assert_eq!(pane.parser.screen().cursor_position(), (3, 0));
    }
    #[test]
    fn shrinking_keeps_latest_output_and_prompt_in_view() {
        let c = Console {
            id: 1,
            name: "test".into(),
            host: "localhost".into(),
            port: 2323,
            token: None,
            token_env: None,
        };
        let mut pane = Pane::new(1, &c, true);
        pane.output(b"LATEST OUTPUT\nPS5:~ $ ");
        pane.resize(10, 60);
        assert!(pane.parser.screen().contents().contains("LATEST OUTPUT"));
        assert!(
            pane.parser
                .screen()
                .contents()
                .trim_end()
                .ends_with("PS5:~ $")
        );
        pane.scroll(5);
        assert!(pane.parser.screen().scrollback() > 0);
        pane.parser.screen_mut().set_scrollback(0);
        pane.resize(30, 80);
        assert!(pane.parser.screen().contents().contains("LATEST OUTPUT"));
    }
    #[test]
    fn resize_does_not_interrupt_a_fragmented_ansi_sequence() {
        let c = Console {
            id: 1,
            name: "test".into(),
            host: "localhost".into(),
            port: 2323,
            token: None,
            token_env: None,
        };
        let mut p = Pane::new(1, &c, true);
        p.output(b"\x1b[38;2;1;");
        p.resize(10, 60);
        p.output(b"2;3mX");
        let (r, col) = p.parser.screen().cursor_position();
        assert_eq!(
            p.parser.screen().cell(r, col - 1).unwrap().fgcolor(),
            vt100::Color::Rgb(1, 2, 3)
        );
        p.output(&[0xc3]);
        p.resize(8, 60);
        p.output(&[0xa8]);
        assert!(p.parser.screen().contents().contains('è'));
    }
}
