#pragma once

#define PSXTERM_VERSION_MAJOR 0
#define PSXTERM_VERSION_MINOR 1
#define PSXTERM_VERSION_PATCH 0
#define PSXTERM_VERSION_STRING "0.1.0"
#define PSXTERM_PROTOCOL_NAME "PTTY/1"

#define PSXTERM_MAX_SESSIONS_DEFAULT 8
#define PSXTERM_DEFAULT_PORT 2323
